### ISSUE TITLE
Any plans on a NuGet package (hint: AspNet.Identity.Dapper)?

### ISSUE THREAD

**Issue by loedeman** [whisperdancer/AspNet.Identity.Dapper#7]
Thanks for creating a port to Dapper for ASP.NET Identity management. Are there any plans to create a NuGet package for this functionality, in line with current implementations for ASP.NET Identity management, like EF and MongoDB? I think AspNet.Identity.Dapper would be a great name for this package ;) ...

**Comment by whisperdancer** [comment]
I currently don't have a plan to create a nuget package. Feel free to fork the repo and create one.
